server:
  port: 8081
spring:
  cloud:
    stream:
      bindings:
        email:
          destination: emails
          binder: local_rabbit
          group: ungrupo
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                virtual-host: /
